##########################################################################
#
#  CypherEngine Source Code
#  Copyright (c) 2026 Karlo Siric. All rights reserved.
#
#  File: src/CypherEditor/Geometry/CypherEditorGeometry_Modules.cmake
#  Purpose: Registers Geometry modules added after the core slice.
#  Details: Kept separate from CMakeLists.txt so that new modules (Planar,
#           PlanarRegion, Intermediates, Validation, ...) can land with a
#           single include line and without editing the long core source
#           list that other work touches concurrently. Included at the end
#           of CMakeLists.txt, after both targets exist.
#
##########################################################################

target_sources(CypherEditorGeometry
    PRIVATE
        Document/CypherGeometry_DocumentBrushAttributes.cpp
        Document/CypherGeometry_DocumentBrushAttributes.h
        Document/CypherGeometry_DocumentIdentity.h
        Document/CypherGeometry_DocumentRollback.cpp
        Document/CypherGeometry_DocumentRollback.h
        Document/CypherGeometry_DocumentSurfaces.cpp
        Document/CypherGeometry_DocumentSurfaces.h
        Exchange/CypherGeometry_Fragment.cpp
        Exchange/CypherGeometry_Fragment.h
        Primitives/CypherGeometry_Primitive.cpp
        Primitives/CypherGeometry_Primitive.h
        Operations/Euler/CypherGeometry_Euler.cpp
        Operations/Euler/CypherGeometry_Euler.h
        Procedural/Subdivision/CypherGeometry_SubdivisionSurface.cpp
        Procedural/Subdivision/CypherGeometry_SubdivisionSurface.h
        Procedural/Displacement/CypherGeometry_Displacement.cpp
        Procedural/Displacement/CypherGeometry_Displacement.h
        Modifiers/CypherGeometry_ModifierStack.cpp
        Modifiers/CypherGeometry_ModifierStack.h
        Csg/CypherGeometry_CsgTypes.h
        Csg/InputNormalization/CypherGeometry_CsgInput.cpp
        Csg/InputNormalization/CypherGeometry_CsgInput.h
        Csg/BroadPhase/CypherGeometry_CsgBroadPhase.cpp
        Csg/BroadPhase/CypherGeometry_CsgBroadPhase.h
        Csg/Predicates/CypherGeometry_CsgPredicates.cpp
        Csg/Predicates/CypherGeometry_CsgPredicates.h
        Csg/Intersections/CypherGeometry_CsgIntersections.cpp
        Csg/Intersections/CypherGeometry_CsgIntersections.h
        Csg/Corefinement/CypherGeometry_CsgCorefine.cpp
        Csg/Corefinement/CypherGeometry_CsgCorefine.h
        Csg/CellComplex/CypherGeometry_CsgCells.cpp
        Csg/CellComplex/CypherGeometry_CsgCells.h
        Csg/CoplanarOverlay/CypherGeometry_CsgCoplanar.cpp
        Csg/CoplanarOverlay/CypherGeometry_CsgCoplanar.h
        Csg/Classification/CypherGeometry_CsgClassify.cpp
        Csg/Classification/CypherGeometry_CsgClassify.h
        Csg/Expression/CypherGeometry_CsgExpression.cpp
        Csg/Expression/CypherGeometry_CsgExpression.h
        Csg/BoundaryExtraction/CypherGeometry_CsgBoundary.cpp
        Csg/BoundaryExtraction/CypherGeometry_CsgBoundary.h
        Csg/AttributeTransfer/CypherGeometry_CsgAttributes.cpp
        Csg/AttributeTransfer/CypherGeometry_CsgAttributes.h
        Csg/Stitching/CypherGeometry_CsgStitch.cpp
        Csg/Stitching/CypherGeometry_CsgStitch.h
        Csg/Reconstruction/CypherGeometry_CsgReconstruct.cpp
        Csg/Reconstruction/CypherGeometry_CsgReconstruct.h
        Csg/Cleanup/CypherGeometry_CsgCleanup.cpp
        Csg/Cleanup/CypherGeometry_CsgCleanup.h
        Csg/Mesh/CypherGeometry_CsgMesh.cpp
        Csg/Mesh/CypherGeometry_CsgMesh.h
        Csg/Brush/CypherGeometry_CsgBrush.cpp
        Csg/Brush/CypherGeometry_CsgBrush.h
        Csg/Operations/CypherGeometry_CsgOperations.cpp
        Csg/Operations/CypherGeometry_CsgOperations.h
        Cook/CypherGeometry_CookSurfaces.cpp
        Cook/CypherGeometry_CookSurfaces.h
        Cook/Navigation/CypherGeometry_CookNavigation.cpp
        Cook/Navigation/CypherGeometry_CookNavigation.h
        Cook/Batching/CypherGeometry_CookBatching.cpp
        Cook/Batching/CypherGeometry_CookBatching.h
        Cook/Visibility/CypherGeometry_CookVisibility.cpp
        Cook/Visibility/CypherGeometry_CookVisibility.h
        Cook/Lighting/CypherGeometry_CookLighting.cpp
        Cook/Lighting/CypherGeometry_CookLighting.h
        Cook/CompilerInterchange/CypherGeometry_CompilerInterchange.cpp
        Cook/CompilerInterchange/CypherGeometry_CompilerInterchange.h
        Serialization/CypherGeometry_SurfaceSerialization.cpp
        Serialization/CypherGeometry_SurfaceSerialization.h
        Representations/Mesh/CypherGeometry_MeshQuadSlice.cpp
        Representations/Mesh/CypherGeometry_MeshQuadSlice.h
        Constraints/CypherGeometry_Workplane.cpp
        Constraints/CypherGeometry_Workplane.h
        Operations/Painting/CypherGeometry_MeshPaint.cpp
        Operations/Painting/CypherGeometry_MeshPaint.h
        Operations/UvAlignment/CypherGeometry_MeshUvTransform.cpp
        Operations/UvAlignment/CypherGeometry_MeshUvTransform.h
        Representations/Mesh/CypherGeometry_MeshBridge.cpp
        Representations/Mesh/CypherGeometry_MeshBridge.h
        Operations/Topology/CypherGeometry_MeshSourceBridge.cpp
        Operations/Topology/CypherGeometry_MeshSourceBridge.h
        Representations/Mesh/CypherGeometry_MeshMerge.cpp
        Representations/Mesh/CypherGeometry_MeshMerge.h
        Operations/Topology/CypherGeometry_MeshSourceMerge.cpp
        Operations/Topology/CypherGeometry_MeshSourceMerge.h
        Representations/Mesh/CypherGeometry_MeshSlice.cpp
        Representations/Mesh/CypherGeometry_MeshSlice.h
        Operations/Cutting/CypherGeometry_MeshSourceSlice.cpp
        Operations/Cutting/CypherGeometry_MeshSourceSlice.h
        Operations/Construction/CypherGeometry_BrushAuthoring.cpp
        Operations/Construction/CypherGeometry_BrushAuthoring.h
        Operations/Construction/CypherGeometry_BrushShapes.cpp
        Operations/Construction/CypherGeometry_BrushShapes.h
        Operations/UvAlignment/CypherGeometry_UvTools.cpp
        Operations/UvAlignment/CypherGeometry_UvTools.h
        Operations/Construction/CypherGeometry_BrushPatches.cpp
        Operations/Construction/CypherGeometry_BrushPatches.h
        Representations/Patch/CypherGeometry_PatchResize.cpp
        Representations/Patch/CypherGeometry_PatchResize.h
        Operations/Construction/CypherGeometry_BrushSweep.cpp
        Operations/Construction/CypherGeometry_BrushSweep.h
        Operations/VertexManip/CypherGeometry_BrushVertexClump.cpp
        Operations/VertexManip/CypherGeometry_BrushVertexClump.h
        Selection/CypherGeometry_BrushFaceQueries.cpp
        Selection/CypherGeometry_BrushFaceQueries.h
        Attributes/Propagation/CypherGeometry_MeshAttributeTransfer.cpp
        Attributes/Propagation/CypherGeometry_MeshAttributeTransfer.h
        Attributes/Propagation/CypherGeometry_MeshEditBracket.h
        Attributes/Propagation/CypherGeometry_MeshCornerNormals.cpp
        Attributes/Propagation/CypherGeometry_MeshCornerNormals.h
        Attributes/Schema/CypherGeometry_Attributes_MeshStore.cpp
        Attributes/Schema/CypherGeometry_Attributes_MeshStore.h
        Cook/Collision/CypherGeometry_CookCollision.cpp
        Cook/Collision/CypherGeometry_CookCollision.h
        Cook/DependencyGraph/CypherGeometry_CookBytes.h
        Cook/DependencyGraph/CypherGeometry_CookKeys.cpp
        Cook/DependencyGraph/CypherGeometry_CookKeys.h
        Cook/RenderMesh/CypherGeometry_Cook_RenderMesh.cpp
        Cook/RenderMesh/CypherGeometry_Cook_RenderMesh.h
        Document/CypherGeometry_DocumentMeshes.cpp
        Document/CypherGeometry_DocumentMeshes.h
        Document/CypherGeometry_DocumentMeshSet.cpp
        Document/CypherGeometry_DocumentMeshSet.h
        Document/CypherGeometry_DocumentBrushReplacement.cpp
        Document/CypherGeometry_DocumentBrushReplacement.h
        Exchange/Sanitation/CypherGeometry_Sanitation.cpp
        Exchange/Sanitation/CypherGeometry_Sanitation.h
        Intermediates/CypherGeometry_PointWeld.cpp
        Intermediates/CypherGeometry_PointWeld.h
        Intermediates/PolygonSoup/CypherGeometry_PolygonSoup.cpp
        Intermediates/PolygonSoup/CypherGeometry_PolygonSoup.h
        Intermediates/TriangleSoup/CypherGeometry_TriangleSoup.cpp
        Intermediates/TriangleSoup/CypherGeometry_TriangleSoup.h
        Kernel/CypherGeometry_Kernel_TriangleIntersection.cpp
        Kernel/CypherGeometry_Kernel_TriangleIntersection.h
        Operations/Conversion/CypherGeometry_PlanarExtrude.cpp
        Operations/Conversion/CypherGeometry_PlanarExtrude.h
        Operations/Modeling/CypherGeometry_MeshSourceBevel.cpp
        Operations/Modeling/CypherGeometry_MeshSourceBevel.h
        Operations/Modeling/CypherGeometry_MeshSourceComponents.cpp
        Operations/Modeling/CypherGeometry_MeshSourceComponents.h
        Operations/Modeling/CypherGeometry_MeshLoopSlide.cpp
        Operations/Modeling/CypherGeometry_MeshLoopSlide.h
        Operations/Modeling/CypherGeometry_MeshSourceModeling.cpp
        Operations/Modeling/CypherGeometry_MeshSourceModeling.h
        Operations/Modeling/CypherGeometry_MeshSolidify.cpp
        Operations/Modeling/CypherGeometry_MeshSolidify.h
        Operations/Topology/CypherGeometry_MeshSourceTopology.cpp
        Operations/Topology/CypherGeometry_MeshSourceTopology.h
        Operations/Topology/CypherGeometry_MeshSourceComposition.cpp
        Operations/Topology/CypherGeometry_MeshSourceComposition.h
        Operations/Topology/CypherGeometry_MeshObjectCommands.cpp
        Operations/Topology/CypherGeometry_MeshObjectCommands.h
        Operations/UvAlignment/CypherGeometry_MeshSurfacing.cpp
        Operations/UvAlignment/CypherGeometry_MeshSurfacing.h
        Operations/UvAlignment/CypherGeometry_MeshUvIslands.cpp
        Operations/UvAlignment/CypherGeometry_MeshUvIslands.h
        Planar/CypherGeometry_Planar_Frame.cpp
        Planar/CypherGeometry_Planar_Frame.h
        Planar/CypherGeometry_Planar_Offset.cpp
        Planar/CypherGeometry_Planar_Offset.h
        Planar/CypherGeometry_Planar_Overlay.cpp
        Planar/CypherGeometry_Planar_Overlay.h
        Planar/CypherGeometry_Planar_Segment.cpp
        Planar/CypherGeometry_Planar_Segment.h
        Planar/CypherGeometry_Planar_Triangulate.cpp
        Planar/CypherGeometry_Planar_Triangulate.h
        Procedural/Curves/CypherGeometry_CurveSampling.cpp
        Procedural/Curves/CypherGeometry_CurveSampling.h
        Procedural/Patches/CypherGeometry_PatchPrimitives.cpp
        Procedural/Patches/CypherGeometry_PatchPrimitives.h
        Procedural/Sweeps/CypherGeometry_Sweep.cpp
        Procedural/Sweeps/CypherGeometry_Sweep.h
        Queries/CypherGeometry_PickingQueries.cpp
        Queries/CypherGeometry_PickingQueries.h
        Repair/CypherGeometry_Repair.cpp
        Repair/CypherGeometry_Repair.h
        Representations/CurveNetwork/CypherGeometry_CurveNetwork.cpp
        Representations/CurveNetwork/CypherGeometry_CurveNetwork.h
        Representations/Mesh/CypherGeometry_MeshBoundaryOps.cpp
        Representations/Mesh/CypherGeometry_MeshBoundaryOps.h
        Representations/Mesh/CypherGeometry_MeshBevel.cpp
        Representations/Mesh/CypherGeometry_MeshBevel.h
        Representations/Mesh/CypherGeometry_MeshKnife.cpp
        Representations/Mesh/CypherGeometry_MeshKnife.h
        Representations/Mesh/CypherGeometry_MeshLoopTraversal.cpp
        Representations/Mesh/CypherGeometry_MeshLoopTraversal.h
        Representations/Mesh/CypherGeometry_MeshPlanar.h
        Representations/Mesh/CypherGeometry_MeshRecordAccess.h
        Representations/Mesh/CypherGeometry_MeshVertexMove.cpp
        Representations/Mesh/CypherGeometry_MeshVertexMove.h
        Representations/HeightField/CypherGeometry_HeightField.cpp
        Representations/HeightField/CypherGeometry_HeightField.h
        Representations/Mesh/CypherGeometry_MeshSource.cpp
        Representations/Mesh/CypherGeometry_MeshSource.h
        Representations/Patch/CypherGeometry_Patch.cpp
        Representations/Patch/CypherGeometry_Patch.h
        Representations/PlanarRegion/CypherGeometry_PlanarRegion.cpp
        Representations/PlanarRegion/CypherGeometry_PlanarRegion.h
        Representations/PlanarRegion/CypherGeometry_PlanarRegionValidation.cpp
        Representations/PlanarRegion/CypherGeometry_PlanarRegionValidation.h
        Serialization/CypherGeometry_MeshSerialization.cpp
        Serialization/CypherGeometry_MeshSerialization.h
        Selection/CypherGeometry_MeshSelection.cpp
        Selection/CypherGeometry_MeshSelection.h
        Selection/CypherGeometry_MeshSelectionQueries.cpp
        Selection/CypherGeometry_MeshSelectionQueries.h
        Tessellation/CypherGeometry_HeightFieldTessellation.cpp
        Tessellation/CypherGeometry_HeightFieldTessellation.h
        Tessellation/CypherGeometry_MeshTessellation.cpp
        Tessellation/CypherGeometry_MeshTessellation.h
        Tessellation/CypherGeometry_PatchTessellation.cpp
        Tessellation/CypherGeometry_PatchTessellation.h
        Transactions/CypherGeometry_MeshDelta.cpp
        Transactions/CypherGeometry_MeshDelta.h
        Transactions/CypherGeometry_MeshSetDelta.cpp
        Transactions/CypherGeometry_MeshSetDelta.h
        Transactions/CypherGeometry_MeshTransaction.cpp
        Transactions/CypherGeometry_MeshTransaction.h
        Validation/CypherGeometry_MeshGeometricValidation.cpp
        Validation/CypherGeometry_MeshGeometricValidation.h
)

target_include_directories(CypherEditorGeometry
    PUBLIC
        "${CMAKE_CURRENT_SOURCE_DIR}/Attributes/Propagation"
        "${CMAKE_CURRENT_SOURCE_DIR}/Csg"
        "${CMAKE_CURRENT_SOURCE_DIR}/Csg/AttributeTransfer"
        "${CMAKE_CURRENT_SOURCE_DIR}/Csg/BoundaryExtraction"
        "${CMAKE_CURRENT_SOURCE_DIR}/Csg/Brush"
        "${CMAKE_CURRENT_SOURCE_DIR}/Csg/Operations"
        "${CMAKE_CURRENT_SOURCE_DIR}/Csg/BroadPhase"
        "${CMAKE_CURRENT_SOURCE_DIR}/Csg/CellComplex"
        "${CMAKE_CURRENT_SOURCE_DIR}/Csg/Classification"
        "${CMAKE_CURRENT_SOURCE_DIR}/Csg/Cleanup"
        "${CMAKE_CURRENT_SOURCE_DIR}/Csg/CoplanarOverlay"
        "${CMAKE_CURRENT_SOURCE_DIR}/Csg/Corefinement"
        "${CMAKE_CURRENT_SOURCE_DIR}/Csg/Expression"
        "${CMAKE_CURRENT_SOURCE_DIR}/Csg/InputNormalization"
        "${CMAKE_CURRENT_SOURCE_DIR}/Csg/Intersections"
        "${CMAKE_CURRENT_SOURCE_DIR}/Csg/Mesh"
        "${CMAKE_CURRENT_SOURCE_DIR}/Csg/Predicates"
        "${CMAKE_CURRENT_SOURCE_DIR}/Csg/Reconstruction"
        "${CMAKE_CURRENT_SOURCE_DIR}/Csg/Stitching"
        "${CMAKE_CURRENT_SOURCE_DIR}/Cook"
        "${CMAKE_CURRENT_SOURCE_DIR}/Cook/Batching"
        "${CMAKE_CURRENT_SOURCE_DIR}/Cook/CompilerInterchange"
        "${CMAKE_CURRENT_SOURCE_DIR}/Cook/Lighting"
        "${CMAKE_CURRENT_SOURCE_DIR}/Cook/Navigation"
        "${CMAKE_CURRENT_SOURCE_DIR}/Cook/Visibility"
        "${CMAKE_CURRENT_SOURCE_DIR}/Cook/Collision"
        "${CMAKE_CURRENT_SOURCE_DIR}/Cook/DependencyGraph"
        "${CMAKE_CURRENT_SOURCE_DIR}/Cook/RenderMesh"
        "${CMAKE_CURRENT_SOURCE_DIR}/Exchange"
        "${CMAKE_CURRENT_SOURCE_DIR}/Exchange/Sanitation"
        "${CMAKE_CURRENT_SOURCE_DIR}/Intermediates"
        "${CMAKE_CURRENT_SOURCE_DIR}/Intermediates/PolygonSoup"
        "${CMAKE_CURRENT_SOURCE_DIR}/Intermediates/TriangleSoup"
        "${CMAKE_CURRENT_SOURCE_DIR}/Modifiers"
        "${CMAKE_CURRENT_SOURCE_DIR}/Operations/Conversion"
        "${CMAKE_CURRENT_SOURCE_DIR}/Operations/Modeling"
        "${CMAKE_CURRENT_SOURCE_DIR}/Operations/Construction"
        "${CMAKE_CURRENT_SOURCE_DIR}/Operations/Euler"
        "${CMAKE_CURRENT_SOURCE_DIR}/Operations/Painting"
        "${CMAKE_CURRENT_SOURCE_DIR}/Operations/Topology"
        "${CMAKE_CURRENT_SOURCE_DIR}/Planar"
        "${CMAKE_CURRENT_SOURCE_DIR}/Primitives"
        "${CMAKE_CURRENT_SOURCE_DIR}/Procedural/Curves"
        "${CMAKE_CURRENT_SOURCE_DIR}/Procedural/Displacement"
        "${CMAKE_CURRENT_SOURCE_DIR}/Procedural/Patches"
        "${CMAKE_CURRENT_SOURCE_DIR}/Procedural/Subdivision"
        "${CMAKE_CURRENT_SOURCE_DIR}/Procedural/Sweeps"
        "${CMAKE_CURRENT_SOURCE_DIR}/Repair"
        "${CMAKE_CURRENT_SOURCE_DIR}/Representations/CurveNetwork"
        "${CMAKE_CURRENT_SOURCE_DIR}/Representations/HeightField"
        "${CMAKE_CURRENT_SOURCE_DIR}/Representations/Patch"
        "${CMAKE_CURRENT_SOURCE_DIR}/Representations/PlanarRegion"
        "${CMAKE_CURRENT_SOURCE_DIR}/Validation"
)

if (TARGET cypher_editor_geometry_contract_tests)
    target_sources(cypher_editor_geometry_contract_tests
        PRIVATE
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Document/CypherGeometry_DocumentBrushAttributes_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Document/CypherGeometry_DocumentSurfaces_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Exchange/CypherGeometry_Fragment_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Primitives/CypherGeometry_Primitive_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Operations/CypherGeometry_Euler_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Procedural/CypherGeometry_SubdivisionSurface_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Procedural/CypherGeometry_Displacement_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Modifiers/CypherGeometry_ModifierStack_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Csg/CypherGeometry_CsgMesh_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Csg/CypherGeometry_CsgOperations_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Cook/CypherGeometry_CookProducts_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Representations/CypherGeometry_MeshSlice_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Representations/CypherGeometry_MeshMerge_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Representations/CypherGeometry_MeshBridge_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Operations/CypherGeometry_MeshUvTransform_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Operations/CypherGeometry_MeshPaint_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Constraints/CypherGeometry_Workplane_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Representations/CypherGeometry_MeshQuadSlice_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Operations/CypherGeometry_BrushAuthoring_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Operations/CypherGeometry_BrushShapes_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Operations/CypherGeometry_UvTools_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Operations/CypherGeometry_BrushPatches_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Operations/CypherGeometry_BrushSweep_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Operations/CypherGeometry_BrushFaceEditing_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Attributes/CypherGeometry_MeshAttributes_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Cook/CypherGeometry_CookCollision_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Cook/CypherGeometry_Cook_RenderMesh_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Document/CypherGeometry_DocumentMeshes_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Document/CypherGeometry_DocumentMeshSet_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Document/CypherGeometry_DocumentBrushReplacement_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Intermediates/CypherGeometry_Intermediates_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Operations/CypherGeometry_MeshLoopSlide_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Operations/CypherGeometry_MeshObjectCommands_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Operations/CypherGeometry_MeshSourceEdits_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Operations/CypherGeometry_MeshSourceComposition_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Operations/CypherGeometry_MeshSolidify_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Operations/CypherGeometry_MeshUvIslands_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Operations/CypherGeometry_PlanarExtrude_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Planar/CypherGeometry_Planar_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Planar/CypherGeometry_Planar_Offset_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Planar/CypherGeometry_Planar_Overlay_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Procedural/CypherGeometry_Curves_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Procedural/CypherGeometry_PatchPrimitives_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Queries/CypherGeometry_PickingQueries_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Repair/CypherGeometry_Repair_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Selection/CypherGeometry_MeshSelection_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Selection/CypherGeometry_MeshSelectionQueries_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Representations/CypherGeometry_HeightField_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Representations/CypherGeometry_MeshBoundaryOps_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Representations/CypherGeometry_MeshFanInvariant_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Representations/CypherGeometry_MeshBevel_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Representations/CypherGeometry_MeshKnife_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Representations/CypherGeometry_MeshSource_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Representations/CypherGeometry_Patch_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Validation/CypherGeometry_MeshGeometricValidation_Tests.cpp"
    )
endif()
