##########################################################################
#
#  CypherEngine Source Code
#  Copyright (c) 2026 Karlo Siric. All rights reserved.
#
#  File: src/CypherEditor/Geometry/CypherEditorGeometry_Modules.cmake
#  Purpose: Registers Geometry modules added after the core slice.
#  Details: Kept separate from CMakeLists.txt so that new modules (Planar,
#           PlanarRegion, Intermediates, Validation, ...) can land with a
#           single include line and without editing the long core source
#           list that other work touches concurrently. Included at the end
#           of CMakeLists.txt, after both targets exist.
#
##########################################################################

target_sources(CypherEditorGeometry
    PRIVATE
        Brush/CypherGeometry_BrushAuthoring.cpp
        Brush/CypherGeometry_BrushAuthoring.h
        Brush/CypherGeometry_BrushPatches.cpp
        Brush/CypherGeometry_BrushPatches.h
        Brush/CypherGeometry_BrushShapes.cpp
        Brush/CypherGeometry_BrushShapes.h
        Brush/CypherGeometry_BrushSweep.cpp
        Brush/CypherGeometry_BrushSweep.h
        Brush/CypherGeometry_BrushVertexClump.cpp
        Brush/CypherGeometry_BrushVertexClump.h
        Cook/CypherGeometry_CompilerInterchange.cpp
        Cook/CypherGeometry_CompilerInterchange.h
        Cook/CypherGeometry_Cook_RenderMesh.cpp
        Cook/CypherGeometry_Cook_RenderMesh.h
        Cook/CypherGeometry_CookBatching.cpp
        Cook/CypherGeometry_CookBatching.h
        Cook/CypherGeometry_CookBytes.h
        Cook/CypherGeometry_CookCollision.cpp
        Cook/CypherGeometry_CookCollision.h
        Cook/CypherGeometry_CookKeys.cpp
        Cook/CypherGeometry_CookKeys.h
        Cook/CypherGeometry_CookLighting.cpp
        Cook/CypherGeometry_CookLighting.h
        Cook/CypherGeometry_CookNavigation.cpp
        Cook/CypherGeometry_CookNavigation.h
        Cook/CypherGeometry_CookSurfaces.cpp
        Cook/CypherGeometry_CookSurfaces.h
        Cook/CypherGeometry_CookVisibility.cpp
        Cook/CypherGeometry_CookVisibility.h
        Cook/CypherGeometry_HeightFieldTessellation.cpp
        Cook/CypherGeometry_HeightFieldTessellation.h
        Cook/CypherGeometry_MeshTessellation.cpp
        Cook/CypherGeometry_MeshTessellation.h
        Cook/CypherGeometry_PatchTessellation.cpp
        Cook/CypherGeometry_PatchTessellation.h
        Core/CypherGeometry_Attributes_MeshStore.cpp
        Core/CypherGeometry_Attributes_MeshStore.h
        Core/CypherGeometry_Kernel_TriangleIntersection.cpp
        Core/CypherGeometry_Kernel_TriangleIntersection.h
        Core/CypherGeometry_Planar_Frame.cpp
        Core/CypherGeometry_Planar_Frame.h
        Core/CypherGeometry_Planar_Offset.cpp
        Core/CypherGeometry_Planar_Offset.h
        Core/CypherGeometry_Planar_Overlay.cpp
        Core/CypherGeometry_Planar_Overlay.h
        Core/CypherGeometry_Planar_Segment.cpp
        Core/CypherGeometry_Planar_Segment.h
        Core/CypherGeometry_Planar_Triangulate.cpp
        Core/CypherGeometry_Planar_Triangulate.h
        Csg/CypherGeometry_CsgAttributes.cpp
        Csg/CypherGeometry_CsgAttributes.h
        Csg/CypherGeometry_CsgBoundary.cpp
        Csg/CypherGeometry_CsgBoundary.h
        Csg/CypherGeometry_CsgBroadPhase.cpp
        Csg/CypherGeometry_CsgBroadPhase.h
        Csg/CypherGeometry_CsgBrush.cpp
        Csg/CypherGeometry_CsgBrush.h
        Csg/CypherGeometry_CsgCells.cpp
        Csg/CypherGeometry_CsgCells.h
        Csg/CypherGeometry_CsgClassify.cpp
        Csg/CypherGeometry_CsgClassify.h
        Csg/CypherGeometry_CsgCleanup.cpp
        Csg/CypherGeometry_CsgCleanup.h
        Csg/CypherGeometry_CsgCoplanar.cpp
        Csg/CypherGeometry_CsgCoplanar.h
        Csg/CypherGeometry_CsgCorefine.cpp
        Csg/CypherGeometry_CsgCorefine.h
        Csg/CypherGeometry_CsgExpression.cpp
        Csg/CypherGeometry_CsgExpression.h
        Csg/CypherGeometry_CsgInput.cpp
        Csg/CypherGeometry_CsgInput.h
        Csg/CypherGeometry_CsgIntersections.cpp
        Csg/CypherGeometry_CsgIntersections.h
        Csg/CypherGeometry_CsgMesh.cpp
        Csg/CypherGeometry_CsgMesh.h
        Csg/CypherGeometry_CsgOperations.cpp
        Csg/CypherGeometry_CsgOperations.h
        Csg/CypherGeometry_CsgPredicates.cpp
        Csg/CypherGeometry_CsgPredicates.h
        Csg/CypherGeometry_CsgReconstruct.cpp
        Csg/CypherGeometry_CsgReconstruct.h
        Csg/CypherGeometry_CsgStitch.cpp
        Csg/CypherGeometry_CsgStitch.h
        Csg/CypherGeometry_CsgTypes.h
        Document/CypherGeometry_DocumentBrushAttributes.cpp
        Document/CypherGeometry_DocumentBrushAttributes.h
        Document/CypherGeometry_DocumentBrushReplacement.cpp
        Document/CypherGeometry_DocumentBrushReplacement.h
        Document/CypherGeometry_DocumentIdentity.h
        Document/CypherGeometry_DocumentMeshes.cpp
        Document/CypherGeometry_DocumentMeshes.h
        Document/CypherGeometry_DocumentMeshSet.cpp
        Document/CypherGeometry_DocumentMeshSet.h
        Document/CypherGeometry_DocumentRollback.cpp
        Document/CypherGeometry_DocumentRollback.h
        Document/CypherGeometry_DocumentSurfaces.cpp
        Document/CypherGeometry_DocumentSurfaces.h
        Document/CypherGeometry_Fragment.cpp
        Document/CypherGeometry_Fragment.h
        Document/CypherGeometry_MeshDelta.cpp
        Document/CypherGeometry_MeshDelta.h
        Document/CypherGeometry_MeshSerialization.cpp
        Document/CypherGeometry_MeshSerialization.h
        Document/CypherGeometry_MeshSetDelta.cpp
        Document/CypherGeometry_MeshSetDelta.h
        Document/CypherGeometry_MeshTransaction.cpp
        Document/CypherGeometry_MeshTransaction.h
        Document/CypherGeometry_SurfaceSerialization.cpp
        Document/CypherGeometry_SurfaceSerialization.h
        Mesh/CypherGeometry_Euler.cpp
        Mesh/CypherGeometry_Euler.h
        Mesh/CypherGeometry_MeshAttributeTransfer.cpp
        Mesh/CypherGeometry_MeshAttributeTransfer.h
        Mesh/CypherGeometry_MeshBevel.cpp
        Mesh/CypherGeometry_MeshBevel.h
        Mesh/CypherGeometry_MeshBoundaryOps.cpp
        Mesh/CypherGeometry_MeshBoundaryOps.h
        Mesh/CypherGeometry_MeshBridge.cpp
        Mesh/CypherGeometry_MeshBridge.h
        Mesh/CypherGeometry_MeshCornerNormals.cpp
        Mesh/CypherGeometry_MeshCornerNormals.h
        Mesh/CypherGeometry_MeshEditBracket.h
        Mesh/CypherGeometry_MeshKnife.cpp
        Mesh/CypherGeometry_MeshKnife.h
        Mesh/CypherGeometry_MeshLoopSlide.cpp
        Mesh/CypherGeometry_MeshLoopSlide.h
        Mesh/CypherGeometry_MeshLoopTraversal.cpp
        Mesh/CypherGeometry_MeshLoopTraversal.h
        Mesh/CypherGeometry_MeshMerge.cpp
        Mesh/CypherGeometry_MeshMerge.h
        Mesh/CypherGeometry_MeshObjectCommands.cpp
        Mesh/CypherGeometry_MeshObjectCommands.h
        Mesh/CypherGeometry_MeshPlanar.h
        Mesh/CypherGeometry_MeshQuadSlice.cpp
        Mesh/CypherGeometry_MeshQuadSlice.h
        Mesh/CypherGeometry_MeshRecordAccess.h
        Mesh/CypherGeometry_MeshSlice.cpp
        Mesh/CypherGeometry_MeshSlice.h
        Mesh/CypherGeometry_MeshSolidify.cpp
        Mesh/CypherGeometry_MeshSolidify.h
        Mesh/CypherGeometry_MeshSource.cpp
        Mesh/CypherGeometry_MeshSource.h
        Mesh/CypherGeometry_MeshSourceBevel.cpp
        Mesh/CypherGeometry_MeshSourceBevel.h
        Mesh/CypherGeometry_MeshSourceBridge.cpp
        Mesh/CypherGeometry_MeshSourceBridge.h
        Mesh/CypherGeometry_MeshSourceComponents.cpp
        Mesh/CypherGeometry_MeshSourceComponents.h
        Mesh/CypherGeometry_MeshSourceComposition.cpp
        Mesh/CypherGeometry_MeshSourceComposition.h
        Mesh/CypherGeometry_MeshSourceMerge.cpp
        Mesh/CypherGeometry_MeshSourceMerge.h
        Mesh/CypherGeometry_MeshSourceModeling.cpp
        Mesh/CypherGeometry_MeshSourceModeling.h
        Mesh/CypherGeometry_MeshSourceSlice.cpp
        Mesh/CypherGeometry_MeshSourceSlice.h
        Mesh/CypherGeometry_MeshSourceTopology.cpp
        Mesh/CypherGeometry_MeshSourceTopology.h
        Mesh/CypherGeometry_MeshVertexMove.cpp
        Mesh/CypherGeometry_MeshVertexMove.h
        Mesh/CypherGeometry_SubdivisionSurface.cpp
        Mesh/CypherGeometry_SubdivisionSurface.h
        Operations/CypherGeometry_MeshPaint.cpp
        Operations/CypherGeometry_MeshPaint.h
        Operations/CypherGeometry_MeshSurfacing.cpp
        Operations/CypherGeometry_MeshSurfacing.h
        Operations/CypherGeometry_MeshUvIslands.cpp
        Operations/CypherGeometry_MeshUvIslands.h
        Operations/CypherGeometry_MeshUvTransform.cpp
        Operations/CypherGeometry_MeshUvTransform.h
        Operations/CypherGeometry_ModifierStack.cpp
        Operations/CypherGeometry_ModifierStack.h
        Operations/CypherGeometry_PlanarExtrude.cpp
        Operations/CypherGeometry_PlanarExtrude.h
        Operations/CypherGeometry_Primitive.cpp
        Operations/CypherGeometry_Primitive.h
        Operations/CypherGeometry_UvTools.cpp
        Operations/CypherGeometry_UvTools.h
        Operations/CypherGeometry_Workplane.cpp
        Operations/CypherGeometry_Workplane.h
        Queries/CypherGeometry_BrushFaceQueries.cpp
        Queries/CypherGeometry_BrushFaceQueries.h
        Queries/CypherGeometry_MeshSelection.cpp
        Queries/CypherGeometry_MeshSelection.h
        Queries/CypherGeometry_MeshSelectionQueries.cpp
        Queries/CypherGeometry_MeshSelectionQueries.h
        Queries/CypherGeometry_PickingQueries.cpp
        Queries/CypherGeometry_PickingQueries.h
        Surfaces/CypherGeometry_CurveNetwork.cpp
        Surfaces/CypherGeometry_CurveNetwork.h
        Surfaces/CypherGeometry_CurveSampling.cpp
        Surfaces/CypherGeometry_CurveSampling.h
        Surfaces/CypherGeometry_Displacement.cpp
        Surfaces/CypherGeometry_Displacement.h
        Surfaces/CypherGeometry_HeightField.cpp
        Surfaces/CypherGeometry_HeightField.h
        Surfaces/CypherGeometry_Patch.cpp
        Surfaces/CypherGeometry_Patch.h
        Surfaces/CypherGeometry_PatchPrimitives.cpp
        Surfaces/CypherGeometry_PatchPrimitives.h
        Surfaces/CypherGeometry_PatchResize.cpp
        Surfaces/CypherGeometry_PatchResize.h
        Surfaces/CypherGeometry_PlanarRegion.cpp
        Surfaces/CypherGeometry_PlanarRegion.h
        Surfaces/CypherGeometry_PlanarRegionValidation.cpp
        Surfaces/CypherGeometry_PlanarRegionValidation.h
        Surfaces/CypherGeometry_Sweep.cpp
        Surfaces/CypherGeometry_Sweep.h
        Validation/CypherGeometry_MeshGeometricValidation.cpp
        Validation/CypherGeometry_MeshGeometricValidation.h
        Validation/CypherGeometry_PointWeld.cpp
        Validation/CypherGeometry_PointWeld.h
        Validation/CypherGeometry_PolygonSoup.cpp
        Validation/CypherGeometry_PolygonSoup.h
        Validation/CypherGeometry_Repair.cpp
        Validation/CypherGeometry_Repair.h
        Validation/CypherGeometry_Sanitation.cpp
        Validation/CypherGeometry_Sanitation.h
        Validation/CypherGeometry_TriangleSoup.cpp
        Validation/CypherGeometry_TriangleSoup.h
)

if (TARGET cypher_editor_geometry_contract_tests)
    target_sources(cypher_editor_geometry_contract_tests
        PRIVATE
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Brush/CypherGeometry_BrushAuthoring_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Brush/CypherGeometry_BrushFaceEditing_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Brush/CypherGeometry_BrushPatches_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Brush/CypherGeometry_BrushShapes_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Brush/CypherGeometry_BrushSweep_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Cook/CypherGeometry_Cook_RenderMesh_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Cook/CypherGeometry_CookCollision_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Cook/CypherGeometry_CookProducts_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Core/CypherGeometry_Planar_Offset_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Core/CypherGeometry_Planar_Overlay_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Core/CypherGeometry_Planar_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Csg/CypherGeometry_CsgMesh_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Csg/CypherGeometry_CsgOperations_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Document/CypherGeometry_DocumentBrushAttributes_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Document/CypherGeometry_DocumentBrushReplacement_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Document/CypherGeometry_DocumentMeshes_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Document/CypherGeometry_DocumentMeshSet_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Document/CypherGeometry_DocumentSurfaces_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Document/CypherGeometry_Fragment_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Mesh/CypherGeometry_Euler_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Mesh/CypherGeometry_MeshAttributes_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Mesh/CypherGeometry_MeshBevel_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Mesh/CypherGeometry_MeshBoundaryOps_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Mesh/CypherGeometry_MeshBridge_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Mesh/CypherGeometry_MeshFanInvariant_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Mesh/CypherGeometry_MeshKnife_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Mesh/CypherGeometry_MeshLoopSlide_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Mesh/CypherGeometry_MeshMerge_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Mesh/CypherGeometry_MeshObjectCommands_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Mesh/CypherGeometry_MeshQuadSlice_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Mesh/CypherGeometry_MeshSlice_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Mesh/CypherGeometry_MeshSolidify_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Mesh/CypherGeometry_MeshSource_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Mesh/CypherGeometry_MeshSourceComposition_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Mesh/CypherGeometry_MeshSourceEdits_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Mesh/CypherGeometry_SubdivisionSurface_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Operations/CypherGeometry_MeshPaint_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Operations/CypherGeometry_MeshUvIslands_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Operations/CypherGeometry_MeshUvTransform_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Operations/CypherGeometry_ModifierStack_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Operations/CypherGeometry_PlanarExtrude_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Operations/CypherGeometry_Primitive_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Operations/CypherGeometry_UvTools_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Operations/CypherGeometry_Workplane_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Queries/CypherGeometry_MeshSelection_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Queries/CypherGeometry_MeshSelectionQueries_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Queries/CypherGeometry_PickingQueries_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Surfaces/CypherGeometry_Curves_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Surfaces/CypherGeometry_Displacement_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Surfaces/CypherGeometry_HeightField_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Surfaces/CypherGeometry_Patch_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Surfaces/CypherGeometry_PatchPrimitives_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Validation/CypherGeometry_Intermediates_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Validation/CypherGeometry_MeshGeometricValidation_Tests.cpp"
            "${CYPHERENGINE_ROOT_DIR}/tests/CypherEditor/Geometry/Validation/CypherGeometry_Repair_Tests.cpp"
    )
endif()
